apiVersion: velero.io/v1
kind: Restore
metadata:
  name: ic-something-RESTORE-20210725-182655
  namespace: velero
spec:
  backupName: bate5a2
  includeClusterResources: null
  includedNamespaces:
  - '*'
  includedResources:
  - '*'
