apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-test
  namespace: velero
spec:
  backupName: backup-test
  includedNamespaces:
  - '*'
  includedResources:
  - '*'
  includeClusterResources: null
