apiVersion: velero.io/v1
kind: Restore
metadata:
  name: ic-ayastest1234u-restore-2019069-555
  namespace: velero
spec:
  backupName: ic-ayastest1234u-backup-2019069-555
  includeClusterResources: null
  includedNamespaces:
  - '*'
  includedResources:
  - '*'
